---
title: "Netflix Monitor"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: cosmo
    navbar:
      - { title: "Source Code", href: "https://github.com/ricardobreis/Exploratory-Data-Analysis-Netflix", align: right, icon: "fa-github" }
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyr)
library(lubridate)
library(zoo)
library(ggplot2)
library(plotly)
library(wordcloud)
library(forcats)
library(knitr)

historico <- read.csv("~/R-Projetos/Netflix/NetflixViewingHistory.csv", encoding="UTF-8")

historico$Date <- dmy(historico$Date)

historico <- historico %>%
  filter(year(Date) %in% c(2018, 2019))

# Separando titulo em titulo, temporada e episodio
historico <- historico %>%
  separate(col = Title, into = c("titulo", "temporada", "titulo_episodio"), sep = ': ')

# Filtrando o que for serie
historico_serie <- subset(historico, !is.na(historico$temporada))
historico_serie <- subset(historico, !is.na(historico$titulo_episodio))

historico_serie$ano <- year(historico_serie$Date)

episodios_dia <- historico_serie %>%
  count(Date) %>%
  arrange(desc(n))

episodios_dia$ano <- year(episodios_dia$Date)
episodios_dia <- episodios_dia %>% arrange(Date)
episodios_dia$dia_semana_numero <- wday(episodios_dia$Date)
episodios_dia$dia_semana_nome <- weekdays(episodios_dia$Date, abbreviate = T)
episodios_dia$mes_nome <- months(episodios_dia$Date, abbreviate = T)
episodios_dia$dia_semana_nome <- factor(episodios_dia$dia_semana_nome, levels = rev(c("dom", "seg","ter","qua","qui","sex","sáb")), labels = rev(c("Dom","Seg","Ter","Qua","Qui","Sex","Sáb")))
episodios_dia$mes_nome <- factor(month(episodios_dia$Date),levels = as.character(1:12), labels = c("Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"))
episodios_dia$ano_mes <- factor(as.yearmon(episodios_dia$Date)) 
episodios_dia$semana <- as.numeric(format(episodios_dia$Date,"%W"))
episodios_dia$semana_mes <- ceiling(day(episodios_dia$Date) / 7)

# Filtrando o que for filme
historico_filme <- subset(historico, is.na(historico$titulo_episodio))

historico_filme$dia_semana_nome <- weekdays(historico_filme$Date, abbreviate = T)
historico_filme$mes_nome <- months(historico_filme$Date, abbreviate = T)
historico_filme$ano <- year(historico_filme$Date)

```

Sidebar {data-width=200 .sidebar}
=======================================================================

```{r}
sliderInput("ano_slider", 
            label = "Selecione o Ano:",
            min = 2018, 
            max = 2019, 
            value = c(2018,2019), 
            step = 1)

historico_serie_df <- reactive({

  historico_serie %>%
    filter(ano >= input$ano_slider[1] &
             ano <= input$ano_slider[2])

})

episodios_dia_df <- reactive({

  episodios_dia %>%
    filter(ano >= input$ano_slider[1] &
             ano <= input$ano_slider[2])

})

historico_filme_df <- reactive({

  historico_filme %>%
    filter(ano >= input$ano_slider[1] &
             ano <= input$ano_slider[2])

})

```

Séries {data-icon="fa-television"}
=======================================================================

Row 
-----------------------------------------------------------------------

### Séries

```{r}

renderValueBox({

  total_series <- length(unique(historico_serie_df()$titulo))
  
  valueBox(
    total_series,
    icon = 'fa-chart-line'
  )
})

```

### Episódios

```{r}

renderValueBox({
  total_eps <- length(historico_serie_df()$titulo)
  
  valueBox(
    total_eps,
    icon = 'fa-television'
  )
})

```

### Dias

```{r}

renderValueBox({
  total_dias <- length(unique(historico_serie_df()$Date))
  
  valueBox(
    total_dias,
    icon = 'fa-calendar'
  )
})

```

Row {data-height=300}
-----------------------------------------------------------------------

### Frequência por Dia da Semana

```{r}

renderPlot({
  episodio_dia_semana <- episodios_dia_df() %>%
    count(dia_semana_nome)
  
  ggplot(episodio_dia_semana, aes(dia_semana_nome, n)) +
    geom_col(fill = "#0097d6") +
    coord_polar() +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(size = 15))
})
```

### Frequência por Mês

```{r}

renderPlot({
  episodios_mes <- episodios_dia_df() %>%
    count(mes_nome)
  
  
  ggplot(episodios_mes, aes(mes_nome, n)) +
    geom_col(fill = "#0097d6") +
    coord_polar()  +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(size = 15)) 
})

```

Row {data-height=300}
-----------------------------------------------------------------------

### Heatmap

```{r, fig.width = 15,fig.height = 4}

renderPlot({
  ggplot(episodios_dia_df(), aes(semana_mes, dia_semana_nome, fill = n)) + 
    geom_tile(colour = "white") + 
    facet_grid(year(Date) ~ mes_nome) + 
    scale_fill_gradient(low = "#FFD000", high = "#FF1919") + 
    labs(
      x = "Semana",
      y = "Dia",
      fill = "Nº de Episódios"
    ) +
    theme(axis.text.y = element_text(size = 13),
          axis.text.x = element_text(size = 13)) 
})

```

Row 
-----------------------------------------------------------------------

### Worldcloud de Séries Mais Vistas

```{r, fig.width = 10,fig.height = 6}

renderPlot({
  contagem_nuvem <- historico_serie_df() %>%
    count(titulo) %>%
    arrange(desc(n)) %>%
    top_n(100, n)
  
  wordcloud(
    word = contagem_nuvem$titulo, 
    freq = contagem_nuvem$n,
    max.words = 100,
    colors=brewer.pal(8, "Dark2")
  )
})

```


Filmes {data-icon="fa-film"}
=======================================================================

Row 
-----------------------------------------------------------------------

### Filmes

```{r}

renderValueBox({
  total_filmes <- length(unique(historico_filme_df()$titulo))
  
  valueBox(
    total_filmes,
    icon = 'fa-chart-line'
  )
})

```

### Dias

```{r}

renderValueBox({
  total_dias <- length(unique(historico_filme_df()$Date))
  
  valueBox(
    total_dias,
    icon = 'fa-calendar'
  )
})

```

Row 
-----------------------------------------------------------------------

### Frequência por Dia da Semana

```{r}

renderPlot({
  filme_dia_semana <- historico_filme_df() %>%
    count(dia_semana_nome)
  
  ggplot(filme_dia_semana, aes(dia_semana_nome, n)) +
    geom_col(fill = "#0097d6") +
    coord_polar() +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(size = 15)) 
})
  
```

### Frequência por Mês

```{r}

renderPlot({
  filme_mes <- historico_filme_df() %>%
    count(mes_nome)
  
  
  ggplot(filme_mes, aes(mes_nome, n)) +
    geom_col(fill = "#0097d6") +
    coord_polar()  +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(size = 15)) 
})
  
```
